#!/usr/bin/env python
# VDiff
#
# Copyright (C) 2014 Kenneth S. Kundert

"""vdiff

Opens two files in vimdiff.
Provides single-stroke key mappings to make moving differences between two files 
efficient.

Usage:
    vdiff [options] <lfile> <rfile>

Options:
    -g, --gui   Use gvim (rather than vim).
    -h, --help  Print this helpful message.

Relevant Key Mappings:
{mappings}
"""

# License {{{1
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see http://www.gnu.org/licenses/.


# Imports {{{1
from __future__ import print_function, division
from docopt import docopt
from vdiff import vdiff, mappings
import sys, os

# Main {{{1
try:
    mappingSummary = '\n'.join([
        '    %-9s %s' % (m.key, m.desc) for m in mappings
    ])
    cmdSummary = __doc__.format(mappings = mappingSummary)
    arguments = docopt(cmdSummary)
    useGUI = arguments['--gui']
    lfile = arguments['<lfile>']
    rfile = arguments['<rfile>']
    status = vdiff(lfile, rfile, useGUI)
    sys.exit(status)

except KeyboardInterrupt:
    for each in [lfile, rfile]:
        dn, fn = os.path.split(each)
        swpfile = os.path.join(dn, '.' + fn + '.swp')
        try:
            os.remove(swpfile)
        except OSError as err:
            print(str(err))
    sys.exit('Killed by user')

# vim: set sw=4 sts=4 et:
